apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: otel-role-kubernetes-monitor
rules:
  - apiGroups: [ "" ]
    resources:
      # @feature: kubernetes-monitor; permissions to read resources
      - "endpoints"
      - "pods"
      - "services"
      - "nodes"
      - "nodes/metrics"
      - "nodes/proxy"
    verbs: [ "get", "watch", "list" ]