---
- hosts: ["airgap"]
  become: true
  vars:
    direct_download: false
    default_nke_airgap_folder: /Volumes/data-1/packages/Nutanix/nke/2.8.0
    default_object_airgap_folder: /Volumes/data-1/packages/Nutanix/object/3.6
  roles:
    - dimMaryanto93.ntnx_airgap
      