
- hosts: ["nkp-bastion"]
  become: true
  vars:
    helm_version: 'v3.16.3'
    kubectl_download_filetype: 'archive'
    kubectl_version: '1.29.9'
    kubectl_tmp_directory: '/tmp'
    path_downloaded_airgap: /tmp
    nkp_cli_dir_path: /opt/nkp-cli
    nkp_filename: nkp-cli_linux_amd64.tar.gz
    kib_filename: kib_linux_amd64.tar.gz
  tasks:
    - include_role: 
        name: dimmaryanto93.kubectl
    - include_role: 
        name: dimmaryanto93.helm_charts
    - name: Install and configure docker
      block:
        - include_role: 
            name: dimmaryanto93.docker
        - ansible.builtin.file:
            path: "/etc/docker/certs.d/{{ airgap_domain }}{{ airgap_port | default('') }}"
            state: directory
            mode: '0755'
            recurse: yes
        - ansible.builtin.file:
            path: "/etc/docker/certs.d/{{ registry_domain }}{{ registry_port | default('') }}"
            state: directory
            mode: '0755'
            recurse: yes
    - name: Download or Upload Airgap NKP
      block:
        - name: Check the file NKP Cli was exists 
          stat:
            path: "{{ path_downloaded_airgap }}/{{ nkp_filename }}"
          register: file_nkp_cli_uploaded
        - ansible.builtin.get_url:
            url: "{{ download_nkp_cli_url }}"
            dest: "{{ path_downloaded_airgap }}/{{ nkp_filename }}"
          when: 
            - direct_download == true
            - not file_nkp_cli_uploaded.stat.exists
        - copy:
            src: "{{ upload_nkp_cli_path }}"
            dest: "{{ path_downloaded_airgap }}/{{ nkp_filename }}"
          when: 
            - direct_download == false
            - not file_nkp_cli_uploaded.stat.exists
        - ansible.builtin.file:
            path: "{{ nkp_cli_dir_path }}"
            state: directory
            mode: '0755'
        - name: Extract NKP cli
          ansible.builtin.unarchive:
            src: "{{ path_downloaded_airgap }}/{{ nkp_filename }}"
            dest: "{{ nkp_cli_dir_path }}"
            remote_src: yes
        - ansible.builtin.file:
            src: "{{ nkp_cli_dir_path }}/nkp"
            dest: "/usr/local/bin/nkp"
            state: link
