---
- hosts: ["nkp"]
  become: true
  tasks:
    - command:
        cmd: ethtool --offload ens3 rx-gro-hw off
    - command:
        cmd: nmcli c modify ens3 ethtool.feature-rx-gro-hw off
    - ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - zip
        - unzip
        - tar
        - curl
        - wget
        - git
        - rsync
    - name: Generate ssh key
      block: 
        - openssh_keypair:
            path: .ssh/id_ed25519
            type: ed25519
        - shell: |
            eval "$(ssh-agent)"
            ssh-add .ssh/id_ed25519

- hosts: ["nkp-airgap"]
  become: true
  vars:
    docker_insecure_registries_enabled: false
    path_downloaded_airgap: /tmp/
    airgap_filename: nkp-airgapped-bundle_linux_amd64.tar.gz
  tasks:
    - name: Prepare Private Registry
      block:
      - ansible.builtin.package:
          name: "{{ item }}"
        loop:
          - python3-pip
      - ansible.builtin.pip:
          name: cryptography
          executable: pip3
      - ansible.builtin.file:
          path: "{{ item }}"
          state: directory
          mode: '0755'
        loop:
          - certs
      - shell: 'openssl req -newkey rsa:4096 -nodes -sha256 -keyout certs/domain.key -x509 -days 365 -out certs/domain.crt -subj "/C={{ selfsigned_cert.country_id }}/ST=Indonesia/L=Jakarta/O={{ selfsigned_cert.organization_name }}/OU=IT/CN={{ selfsigned_cert.domain_wildcard }}" -addext "subjectAltName = DNS:{{ selfsigned_cert.domain_wildcard }}"'
      - include_role: 
          name: dimmaryanto93.docker
      - ansible.builtin.file:
          path: "/etc/docker/certs.d/{{ airgap_domain }}{{ airgap_port | default('') }}"
          state: directory
          mode: '0755'
          recurse: yes
      - ansible.builtin.copy:
          src: certs/domain.crt
          dest: "/etc/docker/certs.d/{{ airgap_domain }}{{ airgap_port | default('') }}/registry-ca.crt"
          remote_src: yes
      - ansible.builtin.copy:
          src: certs/domain.key
          dest: "/etc/docker/certs.d/{{ airgap_domain }}{{ airgap_port | default('') }}/registry-ca.key"
          remote_src: yes
    - name: Running private registry
      block:
        - lineinfile:
            path: /etc/hosts
            line: "127.0.0.1 {{ airgap_domain }}"
        - ansible.builtin.file:
            path: "/etc/openregistry/{{ item }}"
            state: directory
            mode: '0755'
          loop:
            - certs
            - auth
        - ansible.builtin.copy:
            src: certs/domain.crt
            dest: "/etc/openregistry/certs/registry-ca.crt"
            remote_src: yes
        - ansible.builtin.copy:
            src: certs/domain.key
            dest: "/etc/openregistry/certs/registry-ca.key"
            remote_src: yes
        - shell: "docker run --rm --entrypoint htpasswd xmartlabs/htpasswd -Bbn '{{ registry.username }}' '{{ registry.password }}' | tee /etc/openregistry/auth/htpasswd"
        - docker_container:
            name: DockerRegistry
            image: registry:2
            state: started
            restart: yes
            volumes:
              - "/mnt/registry:/var/lib/registry:rw"
              - "/etc/openregistry/auth:/auth"
              - "/etc/openregistry/certs:/certs"
            ports:
              - "5000:5000"
            env:
              REGISTRY_AUTH: htpasswd
              REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
              REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
              REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/registry-ca.crt"
              REGISTRY_HTTP_TLS_KEY: "/certs/registry-ca.key"
        - ansible.posix.firewalld:
            port: 5000/tcp
            state: enabled
            permanent: true
            immediate: true
            zone: public
          when: ansible_os_family == 'RedHat'
        - community.general.ufw:
            rule: allow
            port: '5000'
            proto: tcp
          when: ansible_os_family == 'Debian'
    - name: Airgap file bundle
      block:
      - name: Check the file airgap was exists 
        stat:
          path: "{{ path_downloaded_airgap }}/{{ airgap_filename }}"
        register: file_nkp_airgap_uploaded
      - ansible.builtin.get_url:
          url: "{{ download_airgap_url }}"
          dest: "{{ path_downloaded_airgap }}/{{ airgap_filename }}"
        when: 
          - direct_download == true
          - not file_nkp_airgap_uploaded.stat.exists
      - copy:
          src: "{{ upload_airgap_url }}"
          dest: "{{ path_downloaded_airgap }}/{{ airgap_filename }}"
        when: 
          - direct_download == false
          - not file_nkp_airgap_uploaded.stat.exists
      - ansible.builtin.file:
          path: "/opt/nkp-airgap"
          state: directory
          mode: '7777'
      - name: Extract NKP airgaped bundle
        ansible.builtin.unarchive:
          src: '{{ path_downloaded_airgap }}/{{ airgap_filename }}'
          dest: '/opt/nkp-airgap'
          remote_src: yes
    - shell: "ls -d /opt/nkp-airgap/nkp-v* | tail -n 1"
      register: nkp_airgap_dir_loc
    - name: Install NKP cli
      block: 
        - ansible.builtin.copy:
            src: "{{ nkp_airgap_dir_loc.stdout }}/cli/nkp"
            dest: "/usr/local/bin/nkp"
            mode: '0644'
            remote_src: yes
        - ansible.builtin.file:
            src: "{{ nkp_airgap_dir_loc.stdout }}/cli/nkp"
            dest: "/usr/bin/nkp"
            state: link
    - name: Publish file bundle into private registry
      block:
      - shell: "nkp push bundle --bundle ./container-images/konvoy-image-bundle*.tar --to-registry='https://{{ airgap_domain }}{{ airgap_port | default('') }}' --to-registry-username='{{ registry.username }}' --to-registry-password='{{ registry.password }}' --to-registry-insecure-skip-tls-verify"
        args:
          chdir: "{{ nkp_airgap_dir_loc.stdout }}"
      - shell: "nkp push bundle --bundle ./container-images/kommander-image-bundle*.tar --to-registry='https://{{ airgap_domain }}{{ airgap_port | default('') }}' --to-registry-username='{{ registry.username }}' --to-registry-password='{{ registry.password }}' --to-registry-insecure-skip-tls-verify"
        args:
          chdir: "{{ nkp_airgap_dir_loc.stdout }}"
      - shell: "nkp push bundle --bundle ./container-images/nkp-catalog-applications-image-bundle*.tar --to-registry='https://{{ airgap_domain }}{{ airgap_port | default('') }}' --to-registry-username='{{ registry.username }}' --to-registry-password='{{ registry.password }}' --to-registry-insecure-skip-tls-verify"
        args:
          chdir: "{{ nkp_airgap_dir_loc.stdout }}"

- hosts: ["nkp-bastion"]
  become: true
  vars:
    helm_version: 'v3.16.3'
    kubectl_download_filetype: 'archive'
    kubectl_version: '1.29.9'
    kubectl_tmp_directory: '/tmp'
    path_downloaded_airgap: /tmp
    nkp_cli_dir_path: /opt/nkp-cli
    nkp_filename: nkp-cli_linux_amd64.tar.gz
    kib_filename: kib_linux_amd64.tar.gz
  tasks:
    - include_role: 
        name: dimmaryanto93.kubectl
    - include_role: 
        name: dimmaryanto93.helm_charts
    - name: Install and configure docker
      block:
        - include_role: 
            name: dimmaryanto93.docker
        - ansible.builtin.file:
            path: "/etc/docker/certs.d/{{ airgap_domain }}{{ airgap_port | default('') }}"
            state: directory
            mode: '0755'
            recurse: yes
        - ansible.builtin.file:
            path: "/etc/docker/certs.d/{{ registry_domain }}{{ registry_port | default('') }}"
            state: directory
            mode: '0755'
            recurse: yes
    - name: Download or Upload Airgap NKP
      block:
        - name: Check the file NKP Cli was exists 
          stat:
            path: "{{ path_downloaded_airgap }}/{{ nkp_filename }}"
          register: file_nkp_cli_uploaded
        - ansible.builtin.get_url:
            url: "{{ download_nkp_cli_url }}"
            dest: "{{ path_downloaded_airgap }}/{{ nkp_filename }}"
          when: 
            - direct_download == true
            - not file_nkp_cli_uploaded.stat.exists
        - copy:
            src: "{{ upload_nkp_cli_path }}"
            dest: "{{ path_downloaded_airgap }}/{{ nkp_filename }}"
          when: 
            - direct_download == false
            - not file_nkp_cli_uploaded.stat.exists
        - ansible.builtin.file:
            path: "{{ nkp_cli_dir_path }}"
            state: directory
            mode: '0755'
        - name: Extract NKP cli
          ansible.builtin.unarchive:
            src: "{{ path_downloaded_airgap }}/{{ nkp_filename }}"
            dest: "{{ nkp_cli_dir_path }}"
            remote_src: yes
        - ansible.builtin.file:
            src: "{{ nkp_cli_dir_path }}/nkp"
            dest: "/usr/local/bin/nkp"
            state: link
