apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../../components/opensearch-fluentbit

patches:
  - target:
      kind: DaemonSet
      name: fluentd
      namespace: kube-system
    path: fluentbit-replacement.json